---
driver:
  name: gogetkitchen

provisioner:
  name: chef_zero
  install_script_url: >
    http://def-www.default.don/site/chef-bootstrap/install_chef_script_for_lxd.sh

transport:
  name: sftp
  ssh_key: <%= Dir.home + '/.ssh/id_rsa' %>

verifier:
  name: inspec

platforms:
  - name: lxc01
    driver:
      provider: lxd
      template: ubuntu-16.04-chef

suites:
  - name: base
    data_bags_path: data_bags
    verifier:
      inspec_tests:
        - test/smoke/default
