---
driver:
  name: gogetkitchen

provisioner:
  name: chef_zero
  install_strategy: once

transport:
  name: sftp
  ssh_key: <%= Dir.home + '/.ssh/id_rsa' %>

verifier:
  name: inspec

platforms:
  - name: lxc
    driver:
      provider: lxd
      alias: ubuntu-16.04-chef

suites:
  - name: base
    data_bags_path: data_bags
    verifier:
      inspec_tests:
        - test/smoke/default
